# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-20 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publsih',
            field=models.DateField(default=datetime.datetime(2019, 3, 20, 8, 11, 43, 619856, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
